# Generated by Django 5.0.2 on 2024-03-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=300)),
                ('author1', models.CharField(max_length=320)),
                ('author2', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=300)),
                ('summary', models.CharField(max_length=300000)),
                ('binding', models.CharField(max_length=300)),
                ('language', models.CharField(max_length=300)),
                ('edition', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('release', models.DateField()),
                ('price', models.IntegerField()),
                ('isbn', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
