# Generated by Django 5.0.2 on 2024-03-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0003_alter_books_data_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books_data',
            name='author2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
