# Generated by Django 5.0.2 on 2024-03-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0006_alter_books_data_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('company', models.CharField(max_length=200, verbose_name='Company Name')),
                ('street', models.TextField(max_length=200, verbose_name='Street Address')),
                ('landmark', models.TextField(max_length=200, verbose_name='Land Mark')),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100, verbose_name='City ')),
                ('zip_code', models.CharField(max_length=100, verbose_name='pin/Zip code')),
                ('mobile', models.IntegerField(verbose_name='Mobile')),
            ],
        ),
    ]
