# Generated by Django 5.0.2 on 2024-03-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0007_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_address',
            name='landmark',
            field=models.TextField(verbose_name='Land Mark'),
        ),
    ]
