# Generated by Django 5.0.2 on 2024-04-05 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0008_alter_customer_address_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_address',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer_address',
            name='state',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Gujarath', 'Gujarath'), ('Kerala', 'Kerala'), ('Karnataka', 'Karnataka'), ('TamilNadu', 'TamilNadu')], max_length=100),
        ),
    ]
