# Generated by Django 5.0.2 on 2024-04-05 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0009_customer_address_user_alter_customer_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
