# Generated by Django 5.0.2 on 2024-04-05 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0010_alter_customer_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='BooksApp.customers'),
        ),
    ]
