# Generated by Django 5.0.2 on 2024-04-06 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0011_alter_customer_address_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_address',
            old_name='user',
            new_name='customer',
        ),
    ]
