# Generated by Django 5.0.2 on 2024-04-07 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0014_alter_customer_address_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_address',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer_address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BooksApp.customers'),
        ),
    ]
