# Generated by Django 5.0.2 on 2024-04-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0015_remove_customer_address_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_address',
            old_name='user',
            new_name='customer',
        ),
    ]
