# Generated by Django 5.0.2 on 2024-04-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0018_alter_customer_address_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='featured_authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='authorimages')),
                ('content', models.TextField()),
            ],
        ),
    ]
