# Generated by Django 5.0.2 on 2024-04-17 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0019_featured_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('order_date', models.DateField(auto_now=True)),
                ('book', models.ManyToManyField(to='BooksApp.books_data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
