# Generated by Django 5.0.2 on 2024-04-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0021_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_books',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
