# Generated by Django 5.0.2 on 2024-04-23 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0022_cart_books_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_books',
            name='book',
        ),
        migrations.AddField(
            model_name='cart_books',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BooksApp.books_data'),
        ),
    ]
