# Generated by Django 5.0.2 on 2024-04-23 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0023_remove_cart_books_book_cart_books_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_books',
            name='user',
        ),
        migrations.AddField(
            model_name='cart_books',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BooksApp.customers'),
        ),
    ]
