# Generated by Django 5.0.2 on 2024-04-24 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0024_remove_cart_books_user_cart_books_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_books',
            name='customer',
        ),
        migrations.AddField(
            model_name='cart_books',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
